### ISSUE TITLE
Use x/tools/go/packages

### ISSUE THREAD

**Issue by vincepri** [kubernetes/gengo#147]
To better support modules, we should plan to switch to the [x/tools/go/package](https://github.com/golang/tools/tree/master/go/packages) library to scan Go packages.

This issue is a follow up from https://github.com/kubernetes/code-generator/issues/69.

**Comment by tbe** [comment]
I would like to implement this.

As i see it for now, this would replace most of 
- `addDir`
- `importBuildPackage`
- `importPackage`
- `findTypesIn`
- `FindTypes`

As we could get the `types.Package` object for each package during the initial `packages.Load()`, the FindTypes procedure would result very much in a stub (for compatibility) and the universe could be filled during the `import` phase.

Anything i got way off or missed?

**Comment by lavalamp** [comment]
I'd be happy to see this modernized. I don't have the cycles to help much, though.

**Comment by tbe** [comment]
I'll figure it out. I will try to leave exported functions at least functioning from user perspective as they do now.

PR will be up in draft as soon as something working exists.

Am 14. April 2020 23:42:34 MESZ schrieb Daniel Smith <notifications@github.com>:
>I'd be happy to see this modernized. I don't have the cycles to help
>much, though.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/kubernetes/gengo/issues/147#issuecomment-613696114

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by tbe** [comment]
This may have to wait until https://github.com/golang/go/issues/38470 is solved.

**Comment by invidian** [comment]
kubernetes/code-generator#69 is really annoying.

@tbe as golang/go#38470 doesn't seem to see much progress, how about we rename `testdata` package to `internal`? Would it unblock your work?

I did that for testing and all tests passes, so I assume it should be fine? For `go run` test, I had to filter out `k8s.io/gengo/internal`, as `go list` lists those packages. Calling `golang.org/x/tools/go/packages.Load(nil, "k8s.io/gengo/internal/a/...")` also seems fine.

**Comment by invidian** [comment]
Okay, I went waaay to deep with this :joy: 

Sooo, when running code generation on projects like https://github.com/kubernetes-sigs/cluster-api project, generation takes a lot of time.

With `ps` I noticed that this process spawns a lot of `go list ...` commands.

Running with `perf` or `pkg/profile` confirms, that actual Go execution time is only a fraction of total execution time.

If I understand correctly, majority of the time is spent on running commands like:
```sh
go list -e -compiler=gc -tags=ignore_autogenerated -installsuffix= '-f={{.Dir}} {{.ImportPath}} {{.Root}} {{.Goroot}} {{if .Error}}{{.Error}}{{end}}'  -- k8s.io/gengo/types
go list -e -compiler=gc -tags=ignore_autogenerated -installsuffix= '-f={{.Dir}} {{.ImportPath}} {{.Root}} {{.Goroot}} {{if .Error}}{{.Error}}{{end}}'  -- k8s.io/gengo/examples/set-gen
```

Each of this command run by hand takes ~50ms on my machine and they seem to be executed almost linearly according to perf and with Hotspot to analyze:
![Selection_342](https://user-images.githubusercontent.com/16539896/107760921-d4223e00-6d2a-11eb-87b2-1ba4f73c7ccf.png)


Those are triggered by https://github.com/kubernetes/gengo/blob/de9496dff47bef4ff8f45a56096bf50798cba2a5/parser/parse.go#L595.

I played a bit with `x/tools/go/packages` and I was actually able to reproduce the output of `Import()` command using `packages.Load()`. You can find those experiments here: https://github.com/kinvolk/gengo/commit/ce5df5f6a0db2b239a5bbdae96784d07f2626c66

However, this turns out to be slower than original code, as it seems `packages.Load()` invokes other binaries like `cgo`, `compile`, `asm`, `link` etc. There is a related upstream issue here: https://github.com/golang/go/issues/31087.

At this point, I guess there are 2 things to try:
- Add new API to be able to import packages in a bulk. Right now there is only `AddDir()` or `Import()`. Making them take a list of packages or adding new methods which take a list of packages would be good.
- Try paralleling calls to import implementation (either `Import()` or `packages.Load()`) together with bulk import, it may speed things up.

I think before we try more things, it would also be nice to rewrite the whole thing to replace map operations with function calls etc. This would allow to write plain uncached version of the parser, then add caching as an independent module, to keep it separate from other code.

**Comment by vincepri** [comment]
Hey @nikhita @palnabarun, anything I can do to help make this happen? We're hitting a roadblock in Cluster API (as @invidian pointed out above), which is slowing down our verification scripts as well.

**Comment by lavalamp** [comment]
Just a note on testing if you make major surgery-- you should run the k8s code generation steps in the main kubernetes repo using the proposed changes to make sure nothing breaks.

I might be able to squeeze *small* PR reviews in but I still don't have cycles to offer any major help.

**Comment by thockin** [comment]
Will be fixed in v2 (https://github.com/kubernetes/gengo/pull/259)
